### ISSUE TITLE
ENABLE_VIRTUAL_TERMINAL_PROCESSING undeclared (first use in this function)   

### ISSUE THREAD

**Issue by emptyelse** [SyrieYume/RobinPlayer#4]
### 描述
不知道为什么会显示windows.h里的宏未定义的问题，可能是sdk版本的问题
报错如下
main.c: In function 'enableVTMode':
main.c:387:15: error: 'ENABLE_VIRTUAL_TERMINAL_PROCESSING' undeclared (first use in this function)
     dwMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.c:387:15: note: each undeclared identifier is reported only once for each function it appears in
![image](https://github.com/user-attachments/assets/89ae1627-84f7-43d6-8149-32710a1b040a)
### 解决
自己加了这个宏的定义就解决了，可以正常运行了
ps(这个库没咋用过，c写的不多)

**Comment by SyrieYume** [comment]
加上了 `ENABLE_VIRTUAL_TERMINAL_PROCESSING` 的宏定义
