### ISSUE TITLE
关于C99版本的建议

### ISSUE THREAD

**Issue by 14ito** [SyrieYume/RobinPlayer#7]
在dev C＋＋中，部分版本可能无法直接识别for（i＝n;    ;    ），的形式，建议改为
int i;
for(i＝n;  ;  )

**Comment by SyrieYume** [comment]
意思是 Dev C++ 不支持在for循环里定义变量吗？

**Comment by 14ito** [comment]
是的，至少是我所使用的版本不支持。

**Comment by SyrieYume** [comment]
这种情况下更建议修改编译器的C标准吧，把定义循环变量写在for循环里算是常见的写法了。

**Comment by SyrieYume** [comment]
这种情况下更建议修改编译器的C标准吧，把定义循环变量写在for循环里算是常见的写法了。
